-- Criação da base de dados
CREATE DATABASE projetofinal;
GO
USE projetofinal;
GO

-- Criação das tabelas
CREATE TABLE usuario (
  COD_USUARIO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  NOME VARCHAR(60) NOT NULL,
  EMAIL VARCHAR(60) NOT NULL UNIQUE,  
  SENHA BINARY(40) NOT NULL
);

CREATE TABLE colegio (
  COD_COLEGIO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  NOME_COLEGIO VARCHAR(80) NULL
);

CREATE TABLE materia (
  COD_MATERIA INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  NOME_MATERIA VARCHAR(20) NOT NULL,
);

CREATE TABLE assunto (
  COD_ASSUNTO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,  
  NOME_ASSUNTO VARCHAR(20) NULL,
  COD_MATERIA INT NOT NULL FOREIGN KEY REFERENCES materia(COD_MATERIA)
);

CREATE TABLE turma (
  COD_TURMA INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  TURNO CHAR(5) NULL,
  NIVEL VARCHAR(20) NULL,
  COD_COLEGIO INT NOT NULL FOREIGN KEY REFERENCES colegio(COD_COLEGIO)
);

CREATE TABLE cabecalho (
  COD_PROVA INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  DATA_PROVA DATE NULL,
  VALOR_PROVA DECIMAL(3,1) NOT NULL,
  COD_USUARIO INT NOT NULL FOREIGN KEY REFERENCES usuario(COD_USUARIO),
  COD_COLEGIO INT NOT NULL FOREIGN KEY REFERENCES colegio(COD_COLEGIO),
  COD_MATERIA INT NOT NULL FOREIGN KEY REFERENCES materia(COD_MATERIA)
);

CREATE TABLE questao (
  COD_QUESTAO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  TIPO_QUESTAO VARCHAR(20) NOT NULL,
  DESCRICAO_QUESTAO VARCHAR(1500) NOT NULL,
  VALOR_QUESTAO DECIMAL(3,1) NULL,
  COD_MATERIA INT NOT NULL FOREIGN KEY REFERENCES materia(COD_MATERIA)
);

CREATE TABLE opcao (
  COD_OPCAO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  DESCRICAO_OPCAO VARCHAR(150) NULL,
  OPCAO_CORRETA BIT NULL,
  COD_QUESTAO INT NOT NULL FOREIGN KEY REFERENCES questao(COD_QUESTAO)
);

-- Selects nas tabelas criadas
SELECT * FROM usuario;
SELECT * FROM colegio;
SELECT * FROM materia;
SELECT * FROM assunto;
SELECT * FROM turma;
SELECT * FROM cabecalho;
SELECT * FROM questao;
SELECT * FROM opcao;

-- Teste de INSERT
INSERT INTO usuario VALUES(
'Lucas Mariano',
'lucas@gmail.com',
HASHBYTES('SHA1', '123456')
);

INSERT INTO materia VALUES(
'Português'
);

INSERT INTO questao VALUES(
'Múltipla escolha',
'Quem descobriu o Brasil?',
4,
1
);

INSERT INTO opcao VALUES(
'Fernando de Noronha',
0,
1
);

INSERT INTO opcao VALUES(
'Pedro Álvares Cabral',
1,
1
);

-- Teste de UPDATE
UPDATE opcao SET DESCRICAO_OPCAO = 'Pedro Álvares Cabral', OPCAO_CORRETA = 1 WHERE COD_OPCAO = 1;
UPDATE opcao SET DESCRICAO_OPCAO = 'Dom Pedro I', OPCAO_CORRETA = 'FALSE' WHERE COD_OPCAO = 2;

SELECT * FROM opcao;